account:
  - account
  - account.name
  - active_media
  - ad_mode_begin
  - ad_mode_complete
  - bytes_delivered
  - daily_unique_viewers
  - drm_bytes_packaged
  - engagement_score
  - licenses_served
  - live_seconds_streamed
  - play_request
  - play_rate
  - player_load
  - video_engagement_1
  - video_engagement_100
  - video_engagement_25
  - video_engagement_50
  - video_engagement_75
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
browser_type:
  - ad_mode_begin
  - ad_mode_complete
  - browser_type
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
city:
  - ad_mode_begin
  - ad_mode_complete
  - city
  - dma
  - engagement_score
  - play_request
country:
  - ad_mode_begin
  - ad_mode_complete
  - country
  - country_name
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
date:
  - ad_mode_begin
  - ad_mode_complete
  - active_media
  - bytes_delivered
  - daily_unique_viewers
  - date
  - drm_bytes_packaged
  - engagement_score
  - licenses_served
  - live_seconds_streamed
  - play_request
  - play_rate
  - player_load
  - video_engagement_1
  - video_engagement_100
  - video_engagement_25
  - video_engagement_50
  - video_engagement_75
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
date_hour:
  - ad_mode_begin
  - ad_mode_complete
  - date_hour
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
destination_domain:
  - ad_mode_begin
  - ad_mode_complete
  - destination_domain
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
destination_path:
  - ad_mode_begin
  - ad_mode_complete
  - destination_path
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
device_os:
  - ad_mode_begin
  - ad_mode_complete
  - device_os
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
device_manufacturer:
  - ad_mode_begin
  - ad_mode_complete
  - device_manufacturer
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
  - video_seconds_viewed
device_type:
  - ad_mode_begin
  - ad_mode_complete
  - device_type
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
live_stream:
  - bytes_delivered
  - origin_bytes_delivered
  - live_stream
player:
  - ad_mode_begin
  - ad_mode_complete
  - bytes_delivered
  - engagement_score
  - play_request
  - play_rate
  - player
  - player_load
  - player_name
  - video_engagement_1
  - video_engagement_100
  - video_engagement_25
  - video_engagement_50
  - video_engagement_75
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
referrer_domain:
  - ad_mode_begin
  - ad_mode_complete
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - referrer_domain
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
region:
  - ad_mode_begin
  - ad_mode_complete
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - region
  - region_name
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
search_terms:
  - ad_mode_begin
  - ad_mode_complete
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - search_terms
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
social_platform:
  - social_lifetime_seconds_viewed
  - social_lifetime_views
  - social_platform
  - social_seconds_viewed
  - social_views
source_type:
  - ad_mode_begin
  - ad_mode_complete
  - engagement_score
  - play_request
  - play_rate
  - player_load
  - source_type
  - video_impression
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
video:
  - ad_mode_begin
  - ad_mode_complete
  - bytes_delivered
  - engagement_score
  - play_request
  - play_rate
  - video
  - video_duration
  - video_engagement_1
  - video_engagement_100
  - video_engagement_25
  - video_engagement_50
  - video_engagement_75
  - video_impression
  - video_name
  - video_percent_viewed
  - video_seconds_viewed
  - video_view
  - video.reference_id
  - video.name
  - video_download_request
  - video_download_complete
  - video_download_cancellation
  - video_download_error